### ISSUE TITLE
Nested pages

### ISSUE THREAD

**Issue by CyberMew** [formspree/blogophonic-hugo#11]
Hi, new to this, pardon me if I am lacking any knowledge.

I have some issue creating nested pages in markdown, if I want to have just a few plain html files, e.g.:
`/projects/index.html` (works ok) and then link to `/projects/project1/index.html` (gives 404 after restart) and `/projects/project1/showcase.html` (gives 404). I tried adding _index.md in `/projects/project1/` as per the Hugo docs but it did not work.

I can simply do markdown files for `/projects.html` and `/showcase1.html` in the same folder but it would be good to group them together in the folders and have the same domain path as well. Pretty sure I am missing something basic.. can someone point me in the right direction?

These are the commands I used:

```
hugo new --kind page projects/index.md
hugo new --kind page projects/project1/index.md
hugo new --kind page projects/project1/showcase.md
```

**Comment by CyberMew** [comment]
Closing as it is working fine now for some reason (most likely some cache issues).

**Comment by CyberMew** [comment]
Reopened as I thought it was a cache issue but it is not.

Seems like I cannot have both `index.html` for `both /projects/ and /projects/project1/` work simultaneously, but having `_index.md` in `/projects/` will cause `/projects/project1/*` to work well. Any ideas to solve this?

**Comment by rohitdatta** [comment]
Hi @CyberMew! Are you trying to achieve the folder structure so you get the following URLs:

```
/projects
/projects/project1
/projects/project1/showcase
```

**Comment by CyberMew** [comment]
Hi @rohitdatta, just these 2 'folders' with index.html:
```
/projects (/projects/index.html)
/projects/project1 (/projects/project1/index.html)
```
and separate html files for project1, i.e. `/projects/project1/showcase.html` or `/projects/project1/details.html`

**Comment by rohitdatta** [comment]
So when displaying showcase.html or details.html what would be the path for those page?

**Comment by CyberMew** [comment]
It would be `.com/projects/project1/showcase.html` or `.com/projects/project1/details.html`. Not sure if this is possible..

**Comment by rohitdatta** [comment]
Gotcha, you'll want to create a folder structure similar to this:

![image](https://user-images.githubusercontent.com/6260066/119041871-ffd94380-b96b-11eb-947f-46dd9b7107c1.png)

This will create a path like `/projects/project1/showcase` or `/projects/project1/details`. I think you can also make this an [alias](https://gohugo.io/content-management/urls/#example-aliases) if you'd like, or you can use [ugly URLs](https://gohugo.io/content-management/urls/#ugly-urls) if you like to see `details.html` in the URL.

**Comment by CyberMew** [comment]
Sorry for the late reply. Thanks, I tried that, and it didn't work when. Even after removing the nesting, it is still the same unfortunately.. it just shows me this as content for `http://localhost:1313/projects/`:
![image](https://user-images.githubusercontent.com/4715911/119247972-8e460300-bbc0-11eb-880c-aa20a10a0e7e.png)

This is the supposed file contents:
```markdown
---
title: "Projects _index_"
description:
date: 2021-05-19T04:46:00+08:00
draft: false
# layout options are standard (default) or wide-body
layout: standard
show_title_as_headline: false
---

# Projects
etc etc
```
This is the current structure:
![image](https://user-images.githubusercontent.com/4715911/119247998-aa49a480-bbc0-11eb-9e12-877dd907c540.png)

Am I supposed to edit something else? Super weird behaviour..

**Comment by CyberMew** [comment]
I googled and found https://bwaycer.github.io/hugo_tutorial.hugo/content/using-index-md/. Seems like it is indeed using the `_index.md` and is rendering as per `layouts/_default/list.html`, instead of via `layouts/page/standard.html`, hence the `.Content` is not being shown.

Is there anyway to change this, like to get it to recognise as a Page instead of a default List?

**Comment by CyberMew** [comment]
Seems like this is how Hugo works, so they have to be using `_index.md` (`list` type) to configure the intermediate folders as `section` and the deepest nested folder can use `index.md` normally (or can leave it as _index.md..), and I have to do some workaround to get it to work as per https://discourse.gohugo.io/t/layout-doesnt-work-but-type-sets-the-layout-why/32770/9 since this is `list` type and configure the layouts accordingly for `list`. Closing this as it is resolved.
