### ISSUE TITLE
Please correct link to feed

### ISSUE THREAD

**Issue by Brixy** [formspree/blogophonic-hugo#2]
This is a nice clean and configurable theme. Thank you!

The link to feed.xml causes a 404 error.

This is correct:

<https://blogophonic-hugo.netlify.com/index.xml>

**Comment by esquareda** [comment]
@colevscode this worked as expected before the deploy to Netlify, possibly an issue only in the demo?

**Comment by apreshill** [comment]
FYI, this is set here: https://github.com/formspree/blogophonic-hugo/blob/8cb210ded5986f9d3a230887a406a52390403ea5/data/navigation.yaml#L30

**Comment by rohitdatta** [comment]
Fixed in #7
